name: Build Flutter Android

on:
  push:
    branches: [ "ci-cd" ]
  pull_request:
    branches: [ "ci-cd" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Build APK
      run: flutter build apk --release --no-tree-shake-icons

    - name: Upload to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_CLI_TOKEN }}
        groups: testers
        file: build/app/outputs/flutter-apk/app-release.apk
