name: Build Flutter Android

on:
  push:
    branches: [ "fixCICD" ]
  pull_request:
    branches: [ "fixCICD" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Generate code (build_runner)
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3.1.3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
